# Decide on one or the other
ERR=/dev/null
#ERR=err

PYVCOMP=./pyvcomp.py
check:
	@echo  "Checking parser with" \'${PYVCOMP}\' :
	@${PYVCOMP} -d 4 examples/decl.pc      | grep "decl" >${ERR}
	@echo -n "."

test:
	@${PYVCOMP} examples/add2.pc      | grep "'num' '10' 0" >>${ERR}
	@echo -n "."
	@${PYVCOMP} examples/mul.pc       | grep "'num' '6' 0" >>${ERR}
	@echo -n "."
	@${PYVCOMP} examples/mul2.pc      | grep "'num' '24' 0" >>${ERR}
	@echo -n "."
	@${PYVCOMP}  examples/expr.pc     | grep "'num' '7' 0" >>${ERR}
	@echo -n "."
	@${PYVCOMP}  examples/expr2.pc    | grep "'num' '11' 0" >>${ERR}
	@echo -n "."
	@${PYVCOMP} examples/paren.pc     | grep "'num' '15' 0" >>${ERR}
	@echo -n "."
	@${PYVCOMP} examples/paren2.pc    | grep "'num' '25' 0" >>${ERR}
	@echo -n "."
	@${PYVCOMP}  examples/paren3.pc   | grep "'num' '15' 0" >>${ERR}
	@echo -n "."
	@${PYVCOMP}  examples/paren4.pc   | grep "'num' '11' 0" >>${ERR}
	@echo " OK"

lexcheck:
	@echo -n "."
	@${PYVCOMP} -x examples/comm2.pc  | grep "Another"  >>${ERR}
	@echo -n "."
	@${PYVCOMP} -x examples/comm3.pc  | grep "comment \"here\""  >>${ERR}
	@echo -n "."
	@${PYVCOMP} -x examples/comm4.pc  | grep "Doc Comment"  >>${ERR}
	@echo -n "."
	@${PYVCOMP} -x examples/str.pc    | grep "Hello World"  >>${ERR}
	@echo -n "."
	@${PYVCOMP} -x examples/str2.pc   | grep "hello 'old' world"  >>${ERR}
	@echo -n "."
	@${PYVCOMP} -x examples/str3.pc   | grep "hello world" >>${ERR}
	@echo -n "."
	@${PYVCOMP} -x examples/str5.pc   | grep "hello world: 1234 AB :; again " >>${ERR}

	@echo " OK"

